/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IvpSystemRouteImport } from './routes/ivp-system'
import { Route as ReachUsRouteImport } from './routes/reach-us'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as VisionAiRouteImport } from './routes/vision-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IvpSystemRoute = IvpSystemRouteImport.update({
  id: '/ivp-system',
  path: '/ivp-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachUsRoute = ReachUsRouteImport.update({
  id: '/reach-us',
  path: '/reach-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionAiRoute = VisionAiRouteImport.update({
  id: '/vision-ai',
  path: '/vision-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ivp-system': typeof IvpSystemRoute
  '/reach-us': typeof ReachUsRoute
  '/research': typeof ResearchRoute
  '/vision-ai': typeof VisionAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ivp-system': typeof IvpSystemRoute
  '/reach-us': typeof ReachUsRoute
  '/research': typeof ResearchRoute
  '/vision-ai': typeof VisionAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ivp-system': typeof IvpSystemRoute
  '/reach-us': typeof ReachUsRoute
  '/research': typeof ResearchRoute
  '/vision-ai': typeof VisionAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analysis' | '/ivp-system' | '/reach-us' | '/research' | '/vision-ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/analysis' | '/ivp-system' | '/reach-us' | '/research' | '/vision-ai'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/ivp-system'
    | '/reach-us'
    | '/research'
    | '/vision-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  IvpSystemRoute: typeof IvpSystemRoute
  ReachUsRoute: typeof ReachUsRoute
  ResearchRoute: typeof ResearchRoute
  VisionAiRoute: typeof VisionAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ivp-system': {
      id: '/ivp-system'
      path: '/ivp-system'
      fullPath: '/ivp-system'
      preLoaderRoute: typeof IvpSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach-us': {
      id: '/reach-us'
      path: '/reach-us'
      fullPath: '/reach-us'
      preLoaderRoute: typeof ReachUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-ai': {
      id: '/vision-ai'
      path: '/vision-ai'
      fullPath: '/vision-ai'
      preLoaderRoute: typeof VisionAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  IvpSystemRoute: IvpSystemRoute,
  ReachUsRoute: ReachUsRoute,
  ResearchRoute: ResearchRoute,
  VisionAiRoute: VisionAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
